update keystore encryotion

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,11 +18,20 @@ jobs:
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v3
 
-      - name: Decode and set up Keystore file
+      - name: Decode and Write Keystore File
         run: |
-          echo "${{ secrets.KEYSTORE_FILE }}" > my-release-key.jks
+          echo "${{ secrets.KEYSTORE_FILE }}" | openssl base64 -d -out my-release-key.jks
         env:
           KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
+
+      - name: Verify Keystore File
+        run: |
+          if [ -s my-release-key.jks ]; then
+          echo "Keystore file created successfully."
+          ls -l my-release-key.jks
+          else
+          echo "Keystore file is empty or missing!" && exit 1
+          fi
 
       - name: Build the project
         run: ./gradlew assembleRelease --no-daemon
